# Generated by Django 2.1.2 on 2018-12-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractMis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinfo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
