# Generated by Django 2.1.2 on 2018-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractMis', '0003_auto_20181210_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinfo',
            name='price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
